define({
  adapList: [
    ['map', 'collect'],
    ['reduce', 'inject', 'foldl'],
    ['reduceRight', 'foldr'],
    ['find', 'detect'],
    ['filter', 'select'],
    'reject',
    'invoke',
    'pluck',
    'max',
    'min',
    'sortBy',
    'groupBy',
    'sortedIndex',
    'shuffle',
    'toArray',
    'size',
    ['first', 'head'],
    'initial',
    'last',
    ['rest', 'tail'],
    'compact',
    'flatten',
    'without',
    'union',
    'intersection',
    'difference',
    ['uniq', 'unique'],
    'zip',
    'indexOf',
    'lastIndexOf',
    'keys',
    'values',
    ['functions', 'methods'],
    'pick',
    'tap',
    'has',
    'uniqueId',
    'escape',
    'result',
    'template'
  ]
});